site_name: Obol IT
nav:
  - Home: index.md
  - Tags: tags.md
  - 'Notes':
    - Authentication plugin caching_sha2_password cannot be loaded: posts/mysql8_caching_sha2_pass.md
    - Bringing custom logs to Elasticsearch: posts/custom_logs_elastic.md
    - Change MySQL Password Policy Level: posts/mysql_password_policy.md
    - Check size of the MySQL table: posts/mysql_table_size.md
    - Copy files with SCP: posts/scp_transfer.md
    - Create APT repository on CentOS: posts/apt_repo_centos.md
    - Create preseed with LVM and partman: posts/partman_lvm_preseed.md
    - Configure static IP address on CentOS 8: posts/static_ip_centos8.md
    - Copy MySQL database: posts/copy_mysql_database.md
    - Delete branch in git: posts/delete_git_branch.md
    - Extend LVM in Linux: posts/extend_lvm_linux.md
    - Gather or update ansible facts: posts/gather_ansible_facts.md
    - Host is not allowed to connect to this MySQL server: posts/host_not_allowed_connect_mysql.md
    - Install Percona MySQL Server 8 on CentOS 8: posts/install_percona_mysql8.md
    - List and add Iptables rules: posts/iptables_basics.md
    - Move /var to new partition in CentOS: posts/var_to_new_partition.md
    - Refresh snap packages / update snap: posts/snap_refresh.md
    - Repair corrupted USB drive in Linux: posts/repair_corrupted_usb_drive.md
    - Repair corrupted USB drive in Windows: posts/repair_corrupted_usb_drive_win.md
    - Restart port on Cisco device: posts/cisco_port_restart.md
    - Update firmware on Linux: posts/linux_firmware_update.md
    - Use two network gateways with CentOS: posts/two_gateways_centos.md
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.top
  #   - navigation.tabs
  palette:
    - scheme: default
      toggle:
        name: Switch to dark mode
        icon: material/brightness-7
    - scheme: slate
      toggle:
        name: Switch to light mode
        icon: material/brightness-4
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/obol89/
    - icon: fontawesome/brands/github
      link: https://github.com/obol89
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
plugins:
  - search
  - tags:
      tags_file: tags.md
