site_name: Obol IT
nav:
  - Home: index.md
  - Tags: tags.md
  - 'Notes':
    - Create APT repository on CentOS: posts/apt_repo_centos.md
    - Create preseed with LVM and partman: posts/partman_lvm_preseed.md
    - Delete branch in git: posts/delete_git_branch.md
    - Gather or update ansible facts: posts/gather_ansible_facts.md
    - Move /var to new partition in CentOS: posts/var_to_new_partition.md
    - Repair corrupted USB drive in Linux: posts/repair_corrupted_usb_drive.md
    - Repair corrupted USB drive in Windows: posts/repair_corrupted_usb_drive_win.md
    - Use two network gateways with CentOS: posts/two_gateways_centos.md
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
  #   - navigation.tabs
  palette:
    - scheme: default
      toggle:
        name: Switch to dark mode
        icon: material/brightness-7
    - scheme: slate
      toggle:
        name: Switch to light mode
        icon: material/brightness-4
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/obol89/
    - icon: fontawesome/brands/github
      link: https://github.com/obol89
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
plugins:
  - search
  - tags:
      tags_file: tags.md
